export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const RECEIVE_STREAMS = "RECEIVE_STREAMS";
export const REQUEST_STREAMS = "REQUEST_STREAMS";

export const RECEIVE_STREAM = "RECEIVE_STREAM";
export const REQUEST_STREAM = "REQUEST_STREAM";

export const UPDATE_STREAM = "UPDATE_STREAM";
export const REQUEST_UPDATE_STREAM = "REQUEST_UPDATE_STREAM";


export const NEW_STREAM = "NEW_STREAM";
export const REQUEST_NEW_STREAM = "REQUEST_NEW_STREAM";


export const REQUEST_DELETE_STREAM = "REQUEST_DELETE_STREAM";
export const DELETE_STREAM = "DELETE_STREAM";


export const SET_CURRENT_LANG = "SET_CURRENT_LANG";
export const GET_CURRENT_LANG = "GET_CURRENT_LANG"



